"use client";

import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { useQuery } from "convex/react";
import { ShoppingBag, Package } from "lucide-react";
import { api } from "../../../../../convex/_generated/api";
import { CartProvider, useCart } from "@/components/ecommerce/storefront/Cart";
import { Button } from "@/components/ui/button";

function Header({ slug }: { slug: string }) {
  const store = useQuery(api.ecommerce.storefront.getStore, { slug });
  const { count } = useCart();
  const params = useSearchParams();
  const activeCollection = params.get("collection");
  const color = store?.primaryColor ?? "#d4a017";
  return (
    <header className="sticky top-0 z-40 border-b bg-white/90 backdrop-blur">
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-4">
        <Link href={`/ecommerce/storefront/${slug}`} className="flex items-center gap-2 font-semibold">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg text-white" style={{ backgroundColor: color }}>{store?.name?.[0] ?? "S"}</span>
          <span>{store?.name ?? "Store"}</span>
        </Link>
        <nav className="hidden items-center gap-4 overflow-x-auto text-sm md:flex">
          <Link href={`/ecommerce/storefront/${slug}`} className={!activeCollection ? "font-medium" : "text-muted-foreground hover:text-foreground"}>All products</Link>
          {store?.collections.map((c) => (
            <Link key={c._id} href={`/ecommerce/storefront/${slug}?collection=${c.handle}`} className={activeCollection === c.handle ? "font-medium" : "text-muted-foreground hover:text-foreground"}>{c.title}</Link>
          ))}
        </nav>
        <div className="flex items-center gap-2">
          <Button asChild variant="ghost" size="sm"><Link href={`/ecommerce/storefront/${slug}/track`}><Package className="h-4 w-4" /> Track order</Link></Button>
          <Button asChild size="sm" style={{ backgroundColor: color }}><Link href={`/ecommerce/storefront/${slug}/checkout`}><ShoppingBag className="h-4 w-4" /> Cart {count > 0 && <span className="ml-1 rounded-full bg-white/25 px-1.5 text-xs">{count}</span>}</Link></Button>
        </div>
      </div>
    </header>
  );
}

export default function StorefrontLayout({ children }: { children: React.ReactNode }) {
  const { slug } = useParams<{ slug: string }>();
  return (
    <CartProvider slug={slug}>
      <div className="min-h-screen bg-white text-neutral-900">
        <Header slug={slug} />
        <main className="mx-auto max-w-6xl px-4 py-8">{children}</main>
        <footer className="border-t py-8 text-center text-xs text-muted-foreground">
          <p>Storefront generated by Commerce Autopilot · 30-day happiness guarantee · Fast tracked shipping</p>
          <p className="mt-1"><Link href={`/ecommerce/storefront/${slug}/track`} className="underline">Track your order</Link> · <Link href="/ecommerce" className="underline">About the platform</Link></p>
        </footer>
      </div>
    </CartProvider>
  );
}
