import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              disableTransitionOnChange
            >
              <div className="px-10">
                <Navbar
                  logo={{
                    url: "/",
                    src: "https://deifkwefumgah.cloudfront.net/shadcnblocks/block/logos/shadcnblockscom-icon.svg",
                    alt: "DonateNow Logo",
                    title: "DonateNow",
                  }}
                  menu={[
                    { title: "Home", url: "/" },
                    {
                      title: "Campaigns",
                      url: "/campaigns",
                      items: [
                        {
                          title: "Active Campaigns",
                          description:
                            "Browse and support ongoing donation campaigns",
                          icon: "🎯",
                          url: "/campaigns/active",
                        },
                        {
                          title: "Emergency Relief",
                          description:
                            "Urgent campaigns needing immediate support",
                          icon: "🚨",
                          url: "/campaigns/emergency",
                        },
                        {
                          title: "Education",
                          description:
                            "Support educational initiatives worldwide",
                          icon: "📚",
                          url: "/campaigns/education",
                        },
                        {
                          title: "Healthcare",
                          description:
                            "Medical campaigns and health initiatives",
                          icon: "🏥",
                          url: "/campaigns/healthcare",
                        },
                      ],
                    },
                    {
                      title: "How It Works",
                      url: "/how-it-works",
                      items: [
                        {
                          title: "For Donors",
                          description:
                            "Learn how to make secure donations and track impact",
                          icon: "💝",
                          url: "/donors",
                        },
                        {
                          title: "For Organizations",
                          description:
                            "Create and manage fundraising campaigns",
                          icon: "🏢",
                          url: "/organizations",
                        },
                        {
                          title: "Payment Security",
                          description:
                            "Our secure payment processing and data protection",
                          icon: "🔒",
                          url: "/security",
                        },
                        {
                          title: "Impact Tracking",
                          description:
                            "See how your donations make a real difference",
                          icon: "📊",
                          url: "/impact",
                        },
                      ],
                    },
                    { title: "About Us", url: "/about" },
                    { title: "Contact", url: "/contact" },
                  ]}
                  auth={{
                    login: { title: "Sign In", url: "/sign-in" },
                    signup: { title: "Get Started", url: "/sign-up" },
                  }}
                />
              </div>
              {children}
            </ThemeProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
