import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/Navbar";
import { UserSyncProvider } from "@/components/UserSyncProvider";
import { UserSyncStatus } from "@/components/UserSyncStatus";
import {
  Target,
  AlertTriangle,
  BookOpen,
  Heart,
  Building,
  Shield,
  BarChart3,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <UserSyncProvider>
              <div className="px-10 relative z-[1000]">
                <Navbar
                  logo={{
                    url: "/",
                    src: "/logo.png",
                    alt: "goldendoor foundation logo",
                    title: "",
                  }}
                  menu={[
                    { title: "Home", url: "/" },
                    {
                      title: "Campaigns",
                      url: "/campaigns",
                      items: [
                        {
                          title: "Active Campaigns",
                          description:
                            "Browse and support ongoing donation campaigns",
                          icon: <Target className="h-5 w-5" />,
                          url: "/campaigns?status=active",
                        },
                        {
                          title: "Emergency Relief",
                          description:
                            "Urgent campaigns needing immediate support",
                          icon: <AlertTriangle className="h-5 w-5" />,
                          url: "/campaigns?urgency=high",
                        },
                        {
                          title: "Education",
                          description:
                            "Support educational initiatives worldwide",
                          icon: <BookOpen className="h-5 w-5" />,
                          url: "/campaigns?category=Education",
                        },
                        {
                          title: "Healthcare",
                          description:
                            "Medical campaigns and health initiatives",
                          icon: <Heart className="h-5 w-5" />,
                          url: "/campaigns?category=Healthcare",
                        },
                      ],
                    },
                    // {
                    //   title: "How It Works",
                    //   url: "/how-it-works",
                    //   items: [
                    //     {
                    //       title: "For Donors",
                    //       description:
                    //         "Learn how to make secure donations and track impact",
                    //       icon: <Heart className="h-5 w-5" />,
                    //       url: "/donors",
                    //     },
                    //     {
                    //       title: "For Organizations",
                    //       description:
                    //         "Create and manage fundraising campaigns",
                    //       icon: <Building className="h-5 w-5" />,
                    //       url: "/organizations",
                    //     },
                    //     {
                    //       title: "Payment Security",
                    //       description:
                    //         "Our secure payment processing and data protection",
                    //       icon: <Shield className="h-5 w-5" />,
                    //       url: "/security",
                    //     },
                    //     {
                    //       title: "Impact Tracking",
                    //       description:
                    //         "See how your donations make a real difference",
                    //       icon: <BarChart3 className="h-5 w-5" />,
                    //       url: "/impact",
                    //     },
                    //   ],
                    // },
                    { title: "Blog", url: "/blog" },
                    { title: "About Us", url: "/about" },
                    { title: "Contact", url: "/contact" },
                  ]}
                  auth={{
                    login: { title: "Sign In", url: "/sign-in" },
                    signup: { title: "Get Started", url: "/sign-up" },
                  }}
                />
              </div>
              {children}
              {/* <UserSyncStatus /> */}
            </UserSyncProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
